#!/usr/bin/env python3
"""Summarize keyword quality from a generated ceramic trend report."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT_PATH = PROJECT_ROOT / "local_outputs" / "keyword_quality_report.md"
DEFAULT_TOPICS_PATH = PROJECT_ROOT / "config" / "scrapecreators_quality_topics.json"
DEFAULT_OUTPUT_PATH = PROJECT_ROOT / "local_outputs" / "keyword_quality_summary.md"
REPORTS_DIR = PROJECT_ROOT / "reports"


@dataclass
class KeywordQuality:
    keyword: str
    high_count: int = 0
    edge_count: int = 0
    low_count: int = 0
    subreddits: Counter[str] = field(default_factory=Counter)
    examples: list[str] = field(default_factory=list)

    @property
    def total(self) -> int:
        return self.high_count + self.edge_count + self.low_count

    @property
    def signal_score(self) -> int:
        return self.high_count * 3 + self.edge_count - self.low_count * 2

    @property
    def decision(self) -> str:
        if self.total == 0:
            return "本轮无证据，暂不判断"
        if self.low_count > self.high_count:
            return "噪音偏高，建议改写或替换"
        if self.high_count >= 4 and self.low_count == 0:
            return "优先保留"
        if self.high_count >= 2:
            return "继续观察"
        if self.high_count == 1:
            return "样本偏少，再测一轮"
        if self.edge_count > 0:
            return "方向可能相关，建议改写更具体"
        return "证据不足，建议替换或延后"

    @property
    def top_subreddits(self) -> str:
        if not self.subreddits:
            return "暂无"
        return "、".join(f"r/{name}" for name, _count in self.subreddits.most_common(3))

    @property
    def example_text(self) -> str:
        if not self.examples:
            return "暂无"
        return "；".join(self.examples[:2])


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Summarize keyword quality from a report.")
    parser.add_argument(
        "--report",
        default=str(DEFAULT_REPORT_PATH),
        help="Markdown report generated by keyword quality live run.",
    )
    parser.add_argument(
        "--topics",
        default=str(DEFAULT_TOPICS_PATH),
        help="Topic config used by the keyword quality run.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help="Markdown summary output path.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report_path = Path(args.report).expanduser().resolve()
    topics_path = Path(args.topics).expanduser().resolve()
    output_path = Path(args.output).expanduser().resolve()
    topics = load_topics(topics_path)

    if is_inside_path(output_path, REPORTS_DIR):
        print(
            "安全保护：关键词质量摘要不能写入正式 reports/ 目录，请输出到 local_outputs/。",
            file=sys.stderr,
        )
        return 2

    if not report_path.exists():
        write_text(output_path, render_missing_report(report_path, topics))
        print(f"关键词质量报告不存在，已写入说明：{display_path(output_path)}")
        return 0

    summary = summarize_report(report_path, topics)
    write_text(output_path, render_summary(report_path, summary))
    print(f"已生成 {display_path(output_path)}")
    return 0


def load_topics(path: Path) -> list[str]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    raw_topics = payload.get("topics", []) if isinstance(payload, dict) else payload
    if not isinstance(raw_topics, list):
        return []
    return [str(topic).strip() for topic in raw_topics if str(topic).strip()]


def summarize_report(path: Path, topics: list[str]) -> list[KeywordQuality]:
    text = path.read_text(encoding="utf-8")
    summary = {topic: KeywordQuality(keyword=topic) for topic in topics}
    raw_section = extract_section(text, "原始证据/链接")
    for row in parse_evidence_rows(raw_section):
        keyword = row["keyword"]
        if keyword not in summary:
            summary[keyword] = KeywordQuality(keyword=keyword)
        item = summary[keyword]
        level = row["level"]
        if level == "high":
            item.high_count += 1
        elif level == "edge":
            item.edge_count += 1
        elif level == "low":
            item.low_count += 1
        subreddit = row["subreddit"].removeprefix("r/").strip()
        if subreddit and subreddit.lower() != "n/a":
            item.subreddits[subreddit] += 1
        title = row["title"]
        if title and title != "暂无":
            item.examples.append(title)
    return [summary[topic] for topic in sorted(summary, key=lambda key: topics.index(key) if key in topics else 999)]


def extract_section(text: str, heading: str) -> str:
    pattern = re.compile(rf"^##\s+{re.escape(heading)}\s*$", re.MULTILINE)
    match = pattern.search(text)
    if not match:
        return ""
    start = match.end()
    next_heading = re.search(r"^##\s+", text[start:], re.MULTILINE)
    end = start + next_heading.start() if next_heading else len(text)
    return text[start:end].strip()


def parse_evidence_rows(section: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for line in section.splitlines():
        cells = markdown_cells(line)
        if len(cells) < 7:
            continue
        if cells[0] == "相关性" or is_separator_row(cells):
            continue
        level = normalize_level(cells[0])
        if not level:
            continue
        rows.append(
            {
                "level": level,
                "keyword": cells[1],
                "subreddit": cells[2],
                "title": cells[3],
            }
        )
    return rows


def markdown_cells(line: str) -> list[str]:
    stripped = line.strip()
    if not stripped.startswith("|"):
        return []
    cells: list[str] = []
    current: list[str] = []
    escaped = False
    for char in stripped:
        if escaped:
            current.append(char)
            escaped = False
            continue
        if char == "\\":
            escaped = True
            continue
        if char == "|":
            cells.append("".join(current).strip())
            current = []
            continue
        current.append(char)
    cells.append("".join(current).strip())
    if cells and cells[0] == "":
        cells = cells[1:]
    if cells and cells[-1] == "":
        cells = cells[:-1]
    return cells


def is_separator_row(cells: list[str]) -> bool:
    return bool(cells) and all(
        re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells if cell.strip()
    )


def normalize_level(value: str) -> str:
    if "高相关" in value:
        return "high"
    if "边缘" in value:
        return "edge"
    if "跑偏" in value or "低相关" in value or "相关性较低" in value:
        return "low"
    return ""


def render_summary(report_path: Path, summary: list[KeywordQuality]) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# 陶瓷关键词质量摘要",
        "",
        f"- 生成时间：{generated_at}",
        f"- 来源报告：{display_path(report_path)}",
        "- 说明：这是小批量关键词质量复盘，不是正式趋势结论。",
        "",
        "## 关键词质量表",
        "",
        "| 关键词 | 高相关 | 边缘相关 | 跑偏 | 信号分 | 建议 | 主要 subreddit | 样例标题 |",
        "|---|---:|---:|---:|---:|---|---|---|",
    ]
    for item in summary:
        lines.append(
            "| {keyword} | {high} | {edge} | {low} | {score} | {decision} | {subs} | {examples} |".format(
                keyword=escape_table_cell(item.keyword),
                high=item.high_count,
                edge=item.edge_count,
                low=item.low_count,
                score=item.signal_score,
                decision=escape_table_cell(item.decision),
                subs=escape_table_cell(item.top_subreddits),
                examples=escape_table_cell(item.example_text),
            )
        )
    lines.extend(["", "## 下一步建议", ""])
    priority = [item.keyword for item in summary if item.decision == "优先保留"]
    observe = [item.keyword for item in summary if "观察" in item.decision or "再测" in item.decision]
    rewrite = [item.keyword for item in summary if "改写" in item.decision or "替换" in item.decision]
    lines.append(f"- 优先保留：{', '.join(priority) if priority else '暂无'}")
    lines.append(f"- 继续观察：{', '.join(observe) if observe else '暂无'}")
    lines.append(f"- 建议改写/替换：{', '.join(rewrite) if rewrite else '暂无'}")
    lines.append("- 如果某个关键词连续两轮高相关少、跑偏多，下一步应拆成更具体搜索词。")
    return "\n".join(lines) + "\n"


def escape_table_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_missing_report(report_path: Path, topics: list[str]) -> str:
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    return "\n".join(
        [
            "# 陶瓷关键词质量摘要",
            "",
            f"- 生成时间：{generated_at}",
            f"- 来源报告：{display_path(report_path)}",
            "- 状态：尚未找到关键词质量测试报告。",
            "",
            "## 待测试关键词",
            "",
            *(f"- {topic}" for topic in topics),
            "",
            "## 下一步",
            "",
            "- 先运行 `bash scripts/run_keyword_quality_check.sh --dry-run` 检查命令。",
            "- 确认愿意消耗 API 额度后，再运行 `bash scripts/run_keyword_quality_check.sh --confirm-live-api`。",
        ]
    ) + "\n"


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


def is_inside_path(path: Path, parent: Path) -> bool:
    try:
        path.resolve().relative_to(parent.resolve())
    except ValueError:
        return False
    return True


if __name__ == "__main__":
    raise SystemExit(main())
